ifneq (,$(filter newlib,$(USEMODULE)))
  include $(RIOTMAKE)/libc/newlib.mk
endif

ifneq (,$(filter newlib_syscalls_default,$(USEMODULE)))
  include $(RIOTBASE)/sys/newlib_syscalls_default/Makefile.include
endif

ifneq (,$(filter modem,$(USEMODULE)))
  include $(RIOTBASE)/sys/modem/Makefile.include
endif

ifneq (,$(filter printf_float,$(USEMODULE)))
  ifeq (1,$(USE_NANO_SPECS))
    export LINKFLAGS += -u _printf_float
  endif
endif
